### PR TITLE
Make some changes for size data

### PR DESCRIPTION
**Pull request by parlough**
**SpongeAPI** | [SpongeCommon](https://github.com/SpongePowered/SpongeCommon/pull/1492)

This PR makes some changes to SizeData as the keys were mutable bounded values but the data manipulator methods were just values. I also modified some documentation about how modifying these can not always work as intended. 

Please read the common PR for more information and provide as much feedback as possible on documentation and functionality.

### CODE REVIEW

**Review by JBYoshi — APPROVED** [review]

**Review by kashike — APPROVED** [review]

**Review by ST-DDT — APPROVED** [review]

**Comment by parlough** [comment]
Oh man this is embarrassing one second

**Comment by parlough** [comment]
These should be good for a final review/test with the fixes I made last night.

**Comment by parlough** [comment]
Looking for considerations on changing `base` to `width` as it is known internally? Might make more sense as well.

**Comment by NeumimTo** [comment]
I had to guess that "base" is supposed to affect "width".

There seems to be an inconsistence with Entity#getBoundingBox where this method already returns AABB, but size data rely on "base" and "height" - two flaot params.

**Comment by ryantheleach** [comment]
Base isn't width.

Width can be confused for width & depth, when base is used for both.

image

Docs could be written that base affects entities x and z components of the bounding box.

**Comment by liach** [comment]
Can't entities just use any aabb for their shapes?

**Review by gabizou — APPROVED** [review]

**Comment by Cybermaxke** [comment]
@parlough Can you change the use of `Float`s to `Double`s? This makes it more consistent with the rest of the API where almost everything uses `Double`.

**Comment by Cybermaxke** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/23d18da481d6c3e18177df067ac81e8e84ac1cdd

**Pull request closed without merging**
