### PR TITLE
1.14 - Village and Pillage

### PR DESCRIPTION
**Pull request by Cybermaxke**
Updates the API from 1.13 to 1.14

### CODE REVIEW

**Comment by liach** [comment]
Any entity type?

**Comment by Cybermaxke** [comment]
@liach Not yet, this is just auto generated. I haven't looked into those

**Comment by liach** [comment]
Ah. I hope we can interface out village and raid data stored in world save.

**Comment by gabizou** [comment]
Just, uh... Closing since this can be alive in `1.14` branch which will get merges between 1.13 etc.

**Pull request closed without merging**
