### PR TITLE
Add ItemMergeEvent

### PR DESCRIPTION
**Pull request by Aaron1011**
This PR adds an event which is fired when Vanilla attempts to merge two `Item`s together.

Merging occurs when two `Item`s are within 0.5 blocks in either the X or Z axis.

This event allows plugins to detect and cancel `Item` merging.

### CODE REVIEW

**Comment by kenzierocks** [comment]
Probably good for shops.

**Comment by gabizou** [comment]
What would you say to adding this event to #330 ? I have a few events related to Items already being added, would make sense to bundle them up together and avoid conflicts.

**Comment by Aaron1011** [comment]
@gabizou: Sure! However, I noticed that in your `ItemEvent`, you created a new method called `getItem`. My `ItemEvent#getItem` is called `getEntity`, in order to override `getEntity` in `EntityEvent`.

Otherwise, you'll have two methods available - `getItem` and `getEntity`, which are really the same thing.

**Comment by gabizou** [comment]
> @gabizou: Sure! However, I noticed that in your ItemEvent, you created a new method called getItem. My ItemEvent#getItem is called getEntity, in order to override getEntity in EntityEvent.
> 
> Otherwise, you'll have two methods available - getItem and getEntity, which are really the same thing.

Well, one thing to note is that ItemEvent already extends `EntityEvent` which has `getEntity() -> Entity` whereas `getItem() -> Item`. Just instead of overriding and casting, we can just make more sense of the methods themselves.

**Comment by Aaron1011** [comment]
That's true - but what about `getEntity`? It not obvious from the name which one it would return. IMHO, but makes more sense to just override `getEntity.

**Comment by gabizou** [comment]
> That's true - but what about getEntity? It not obvious from the name which one it would return. IMHO, but makes more sense to just override `getEntity.

Sure, overriding works too, but I'd have to do the same to the `HumanEvent`, `LivingEvent`, and `PlayerEvent`, but then again, that is more logical to do as well. Overloading may be a bit messy.

**Comment by gabizou** [comment]
Closing as this event has been added in #330. Thanks for the discussion!

**Pull request closed without merging**
