### PR TITLE
Add methods to create TextFormat

### PR DESCRIPTION
**Pull request by kashike**
`TextFormat` is missing methods to create it.

### CODE REVIEW

**Comment by windy1** [comment]
Hmm well you can actually do `TextFormat.NONE.color(color).style(style);` right now but these seem like a good convenience methods if nothing else. Assigning @Minecrell since `TextFormats` are kind of his deal IIRC.

**Comment by MichaelFedora** [comment]
If nothing else, you could get rid of a lot of the constructors to just have one, and then make the `of` functions supply the `NONE`'s.

**Comment by Minecrell** [comment]
Yep, remove the additional constructors, these were from when they were still public.

**Comment by kashike** [comment]
@Minecrell done

**Comment by MichaelFedora** [comment]
@kashike no your not :P

**Pull request merged**
