### PR TITLE
[WIP] Bugfixes and improvements for selectors

### PR DESCRIPTION
**Pull request by kenzierocks**
SpongeAPI (You're here!) | [SpongeCommon](https://github.com/SpongePowered/SpongeCommon/pull/793)

Changes to accommodate the SpongeCommon PR. See that PR for details.

### CODE REVIEW

**Comment by gabizou** [comment]
@Minecrell thoughts?

**Comment by kenzierocks** [comment]
I know this needs testing, but I haven't had a chance yet.

**Comment by Minecrell** [comment]
@gabizou Should be good to merge as soon as @kenzierocks was able to test his implementation.

**Comment by kenzierocks** [comment]
Marking this as WIP since new selectors and values have been added and the API may need a redesign.

**Comment by stephan-gh** [comment]
@kenzierocks Are you still going to finish this PR?

**Comment by parlough** [comment]
Due to little activity, superseded by https://github.com/SpongePowered/SpongeAPI/pull/1645.

**Pull request closed without merging**
