### PR TITLE
Fix javadocs for MessageSinks#combined and MessageSinkFactory#combined

### PR DESCRIPTION
**Pull request by RobertHerhold**
* Change `transform` --> `transformMessage`
* Change occasional `sink` (array) --> `sinks`

### CODE REVIEW

**Comment by RobertHerhold** [comment]
Just a sec, got something else to push to my fork

**Comment by me4502** [comment]
I see no reason not to merge this PR.
@SpongePowered/developers ?

**Comment by simon816** [comment]
This really belongs in the minor issues list.

Looks fine to me

**Comment by gabizou** [comment]
Move this to the OCD issue #221 and we'll take care of it when someone makes another pass before next release.

**Pull request closed without merging**
