### PR TITLE
Add method to get hand that was used in UseItemStackEvent

### LINKED ISSUE #1464: Get the hand state
It would be nice if there was some way to get the hand state of a player. What I mean with this is to get if a hand is being used (rightclicking). In forge you have stuff like `player.isHandActive()` or `player.getActiveItemStack()`. One example of a use for this would be to do something special if a player is using a shield.

While it is possible to do something similar using `UseItemStackEvent` it feels cubersome, and also doesn't give you information about which hand the action happened in.

### PR DESCRIPTION
**Pull request by ghost**
**SpongeAPI** | [SpongeVanilla](https://github.com/SpongePowered/SpongeVanilla/pull/343)

This pull request adds a method that, when a `UseItemStackEvent` gets fired, gets what hand (out of the main hand and the off-hand) the `ItemStack` that caused the event to be fired was on, as a `HandType` instance. This also fixes some typos in the Javadocs in that class.

This pull request fixes #1464.

### CODE REVIEW

**Comment by ryantheleach** [comment]
Hand needs to return an optional for this to be mod compatible. Several mods allow you to use item stacks from slots other then MainHand and OffHand

**Comment by ghost** [comment]
I think the API for this pull request is more or less done now so I have removed the "[WIP]" marker in the title.

**Review by ST-DDT — APPROVED** [review]

**Comment by gabizou** [comment]
No idea how this got left behind for a year....

**Review by gabizou — APPROVED** [review]

**Review by ST-DDT — APPROVED** [review]

**Comment by ImMorpheus** [comment]
This can't be merged, a SpongeCommon PR is missing.

However I'd prefer something like this: https://github.com/SpongePowered/SpongeAPI/issues/1650

Thoughts ?

**Comment by ImMorpheus** [comment]
Superseded by https://github.com/SpongePowered/SpongeCommon/pull/2191

**Pull request closed without merging**
