### PR TITLE
Added Sneaking to Entities

### PR DESCRIPTION
**Pull request by joshgarde**
Sneaking! Yay!

### CODE REVIEW

**Comment by ryantheleach** [comment]
There is no guarantee that Entities can sneak. So why add these methods? It's already covered in the DataAPI.

**Comment by joshgarde** [comment]
Because there really isn't any way to distinguish between an entity that can sneak and one that can't sneak within MC's code. In MC, an entity - Regardless of type - can sneak.

**Comment by ryantheleach** [comment]
Until when? What happens if they remove sneaking from entities that don't have sneaking animations? If you forcibly make a bat sneak does anything change?

Anyway, it can still be handled by Data manipulators just fine as is, even if *at the moment* all entities can sneak.

**Comment by joshgarde** [comment]
It was worth a try. I suppose future-proofing is favorable over my personal convenience.
As for effects on entities without sneaking animations, I haven't done the testing so I can't say for sure.

**Comment by ryantheleach** [comment]
Yeah the DataAPI at the moment is a little verbose but it's getting better when the Value API is merged.

**Pull request closed without merging**
