### PR TITLE
Rework the entity displacement events

### PR DESCRIPTION
**Pull request by gratimax**
This PR creates a new interface, `EntityDisplaceEvent` for `EntityMoveEvent` and `EntityTeleportEvent` to inherit from.

I would also like to add a 'velocity' property to EntityMoveEvent, but that would probably require some input in terms of when the event is fired, and what changing velocity means.

### CODE REVIEW

**Comment by Bammerbom** [comment]
Isn't EntityMoveEvent a resource-intensive event?

**Comment by ryantheleach** [comment]
Yes? and?

It is/was in bukkit, but I suspect that the lack of bukkit style wrapping classes will make the sponge equivalents at least perform somewhat better.

**Comment by Bammerbom** [comment]
I thought in a discussion before we came to a conclusion to not have a EntityMoveEvent. But maybe I am wrong?

**Comment by ryantheleach** [comment]
Oh right, I'm getting confused with PlayerMoveEvent.

**Comment by gratimax** [comment]
Closed by 51082ef9e10

**Pull request closed without merging**
