### PR TITLE
Provide a way for plugins to check certificate fingerprints

### PR DESCRIPTION
**Pull request by kashike**
[**API**](https://github.com/SpongePowered/SpongeAPI/pull/1007) | [Forge](https://github.com/SpongePowered/SpongeForge/pull/485) | [Vanilla](https://github.com/SpongePowered/SpongeVanilla/pull/200)

This adds the ability for plugins to provide a certificate fingerprint to verify jar signatures. #923

### CODE REVIEW

**Comment by JBYoshi** [comment]
Wait... couldn't someone who wanted to modify the plugin JAR get around the warnings by removing the signature checking code?

**Comment by kenzierocks** [comment]
My thinking on the signatures is not security, but corruption. Easy to forge, but corrupt data will fail to load in most cases.

**Comment by kashike** [comment]
@JBYoshi Of course there's way around checking, there's no way to prevent removing checking.

**Comment by ryantheleach** [comment]
I've also heard of mod authors teaming up to check each others fingerprints and stuff I think.

**Comment by ST-DDT** [comment]
IMO its the servers task to check.

TOFU principle.

Plugin is installed
Server starts and detects that said plugin has a signature. The certificate/signature details are stored by the server in a config file.
Server stops
Plugin will be replaced/gets corrupted
Server starts. The server detects that the plugin should have a signature but detects that the signature is broken or missing and can warn the user appropriately.

**Pull request closed without merging**
