### PR TITLE
Fix event-gen factory

### PR DESCRIPTION
**Pull request by ImMorpheus**
Fix https://github.com/SpongePowered/SpongeAPI/issues/1526

See https://github.com/SpongePowered/SpongeAPI/pull/1977

I've updated the PR (most of those events are gone).

### CODE REVIEW

**Comment by Zidane** [comment]
@ImMorpheus Put these on the lifecycle file exclusions please.

**Comment by dualspiral** [comment]
How is `@NoFactoryMethod` different from an `exclude` directive in the Gradle file? If there is no difference, I'd rather we just add things to the exclude directive, especially as we want to move the factory generation to Common, reducing the exposure of the generator to the API itself.

**Comment by Zidane** [comment]
@dualspiral That is a good point, didn't even think about that.

**Comment by ImMorpheus** [comment]
> How is @NoFactoryMethod different from an exclude directive in the Gradle file? If there is no difference, I'd rather we just add things to the exclude directive, especially as we want to move the factory generation to Common, reducing the exposure of the generator to the API itself.

The exclude directive targets a java file. The annotation targets a type.
This means that 
https://github.com/SpongePowered/SpongeAPI/blob/dc2186f59d37dd277ef8d02b0aef72f3fde2f61a/src/main/java/org/spongepowered/api/event/action/CollideEvent.java#L37-L47
can't be implemented using the exclude directive AFAIK.

I'll move the other ones since this doesn't apply to them.

**Review by gabizou — APPROVED** [review]
LGTM

**Pull request merged**
