### PR TITLE
Require a Cause when opening/closing an inventory

### PR DESCRIPTION
**Pull request by Aaron1011**
This closes https://github.com/SpongePowered/SpongeAPI/issues/930

### CODE REVIEW

**Comment by gabizou** [comment]
Wouldn't this target bleeding?

**Comment by Minecrell** [comment]
You could make the cause optional in master (add 2 new methods) and remove the old method in bleeding.

**Comment by Aaron1011** [comment]
Oops, I meant to target bleeding. I opened it against the wrong branch.

**Comment by ryantheleach** [comment]
It's good to see this merged. But what are the vanilla reasons for an inventory to be closed? player moved out of range of inventory is one.

Should there be some sort of cause factory for plugins to provide compatible causes with the default ones for custom inventories?

**Pull request closed without merging**
