### PR TITLE
Get the World from Chunk.

### PR DESCRIPTION
**Pull request by lexware**

### CODE REVIEW

**Comment by Deamon5550** [comment]
I wonder if this would be better implemented via more generic extent parenting?

See #322

**Comment by modwizcode** [comment]
@Deamon5550 Actually that PR concluded with @sk89q's opinion that Extent parenting isn't something needed/wanted. So I am all for this PR being merged given that this is a specific case where Extent parenting makes sense.

**Comment by sk89q** [comment]
Chunk could have parenting on its own.

**Comment by gratimax** [comment]
Even if we do add more generic extent parenting, this method is pretty harmless since it has very firm standing in how Minecraft works

**Comment by me4502** [comment]
I agree, I see no reason to not merge it.

**Comment by modwizcode** [comment]
I was merely saying that the generic Extent parenting PR wasn't wanted, but this case is an exception. Let's merge this.

**Pull request closed without merging**
