### PR TITLE
Added location.sub() to subtract from Locations

### PR DESCRIPTION
**Pull request by intronate67**
Simply allows for the ability to subtract from a Location because it was requested

### CODE REVIEW

**Comment by DDoS** [comment]
This is acceptable, it's just a little more code for some convenience.

**Comment by intronate67** [comment]
It also makes some stubborn people happy xD

**Comment by me4502** [comment]
I didn't even realize we didn't have this..

**Comment by intronate67** [comment]
xD Yeah i didn't either but two people brought it up.

**Comment by me4502** [comment]
@Zidane Do we have the go-ahead for merging this?

**Comment by Zidane** [comment]
This is up to @DDoS to review and merge.

**Pull request merged**
