### PR TITLE
Add active item data

### PR DESCRIPTION
**Pull request by parlough**
**SpongeAPI** | [SpongeCommon](https://github.com/SpongePowered/SpongeCommon/pull/2042)

Fixes https://github.com/SpongePowered/SpongeAPI/issues/1885

### CODE REVIEW

**Comment by gabizou** [comment]
How does this get handled if it's set server side instead of client?

**Comment by parlough** [comment]
@gabizou I simply return false if they try to set the item stack to anything besides empty. Empty does cancel it, but if they're holding right click it will just become active again.

https://github.com/SpongePowered/SpongeCommon/pull/2042/files#diff-eac4f1c95fc6a64813b25ffe4dde183dR53

**Comment by Cybermaxke** [comment]
The active item feels more like a `Property` to me instead of a `Key` and value.
And maybe extend this PR to provide a active hand: `Optional<HandType>`, right know you don't know which hand is being used. With that knowledge, you can get the active item as well.

**Comment by parlough** [comment]
Hmm currently properties are more things that don't really change once something is created, I think it fits better as data, especially since you can cancel an item being active, such as restarting a player drinking their milk, and other implementions may allow more. 

Relating to the active hand, I'm not really sure how useful that is, because I don't know a situation where it wouldn't be the secondary hand which can be retrieved through the dominant hand property. Then during events it should be part of the context or the event itself.

**Comment by ImMorpheus** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/859d917605f71aeca934c8a6095c533e1a104d2a

**Pull request closed without merging**
