### PR TITLE
Refactor ArmorStand data

### LINKED ISSUE #1052: Add ability to make armor stand a "Marker"
Marker: 1 or 0 (true/false) - if true, ArmorStand's size will be set to 0, have a tiny hitbox and disable interactions with it. May not exist.

http://minecraft.gamepedia.com/Chunk_format#ArmorStand

### PR DESCRIPTION
**Pull request by kashike**
[**API**](https://github.com/SpongePowered/SpongeAPI/pull/1145) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/594)

Resolves #1052, #1100

### CODE REVIEW

**Comment by modwizcode** [comment]
Would you like to address https://github.com/SpongePowered/SpongeCommon/issues/588 with this PR or should I still handle that as a separate change? Since they are somewhat related.

**Comment by kashike** [comment]
@modwizcode I'll leave that to you - you've investigated more so you're currently more familiar.

**Comment by modwizcode** [comment]
Sounds good

**Comment by gabizou** [comment]
@modwizcode why would an issue completely irrelevant be bundled in a different PR? Please don't ask people to do such things...

**Pull request closed without merging**
