### PR TITLE
Add Value.copy().

### PR DESCRIPTION
**Pull request by JBYoshi**
**SpongeAPI** | [SpongeCommon](https://github.com/SpongePowered/SpongeCommon/pull/1907)

### CODE REVIEW

**Comment by gabizou** [comment]
Originally I was for this, but I decided against it for `Value`s because of the nature of them not knowing the types of elements they contain, so they cannot make a true copy by itself, whereas a `DataManipulator` can because it already knows what element types it contains.

**Comment by JBYoshi** [comment]
From what I can see through a look through the `Keys` class, pretty much every value is either an immutable object or a collection of immutable elements handled by a custom `Value` sub-interface (e.g. `ListValue`, `SetValue`, `MapValue`).

Also, I don't think that this would cause any more problems than just using `value.asImmutable().asMutable()`. This would just be a slightly faster method of doing that.

**Comment by JBYoshi** [comment]
Just realized the `OptionalValue` fix is already handled by another PR (#1807). I'll remove that from mine.

**Comment by gabizou** [comment]
I'll agree, as we already can't verify the validity of copies in `asMutable()`/`asImmutable()`, `copy()` already makes sense.

**Review by gabizou — APPROVED** [review]

**Pull request merged**
