### PR TITLE
Add a Catalogue for BlockStates.

### PR DESCRIPTION
**Pull request by me4502**
This PR creates a catalogue system for all blockstates in Minecraft.

### CODE REVIEW

**Comment by Deamon5550** [comment]
So nowhere in those 7800 lines did you stop to think that this was a really stupid idea?

**Comment by me4502** [comment]
@Deamon5550 I didn't write it out by hand, I just generated a list.

I was writing it up so that we had something to discuss off.

**Comment by me4502** [comment]
(For the curious, http://pastebin.com/32DcvV7D)

**Comment by MikaalSky** [comment]
So, tell me why this is stupid?
Length..?

**Comment by me4502** [comment]
Length is the most obvious reason. Most IDEs would fail to generate autocomplete definitions.

**Comment by MikaalSky** [comment]
Got it.

**Comment by ST-DDT** [comment]
However having such a list (split into smaller pieces or provided as a map) could be useful.

**Pull request closed without merging**
