### PR TITLE
Change Return Type of ImmutableBannerData.baseColor() to match BannerData.baseColor()

### PR DESCRIPTION
**Pull request by joshgarde**
It also matches the spec. in Keys.BANNER_BASE_COLOR

### CODE REVIEW

**Comment by AlphaModder** [comment]
I'm confused... what's SneakingData.baseColor()?

**Comment by joshgarde** [comment]
@AlphaModder Those are some old commits. I'm fixing them right now. The main issue here is just ImmutableSneakingData.baseColor().

**Comment by AlphaModder** [comment]
@joshgarde No, I'm asking what does a base color have to do with sneaking?

**Comment by joshgarde** [comment]
@AlphaModder Absolutely nothing. The sneaking stuff is from previous commits to this branch that I used for a previous pull request.

**Comment by AlphaModder** [comment]
@josh Oh, sorry. Your title and previous comment said SneakingData.baseColor(). Did you mean to say BannerData.baseColor()?

**Comment by joshgarde** [comment]
@AlphaModder I'm on copy & paste mode right now. :tongue:

**Comment by AlphaModder** [comment]
@joshgarde Also, if you want to avoid that kinda thing, create copies of your master branch with names like feature/banner-fix. That's how most PRs do it, I believe. That way you can work on multiple things at once without conflicting commits.

**Comment by joshgarde** [comment]
@AlphaModder I know, but I already had the master branch up and didn't have any open pull requests with it so I decided that for this small change I could just do it to the master and have to deal with the rebasing stuff.

**Comment by AlphaModder** [comment]
@joshgarde Ah. I see.

**Comment by Zidane** [comment]
@gabizou 

Need a status update on this.

**Pull request closed without merging**
