### PR TITLE
Update rcon API to make more sense

### PR DESCRIPTION
**Pull request by zml2008**
A lot of the information included in the rcon events is kinda pointless (message id, raw payload), so that was removed.

Also added a disconnect event so both ends of the lifecycle can be tracked
And special command event has been nixed, because that doesn't fit with the commands system well.

Additionally, players and rcon senders now both extend RemoteSource, which provides the getConnection() method, since both are sources connecting from a remote host.

### CODE REVIEW

**Comment by Aaron1011** [comment]
@zml2008: The point of the Rcon api is to be able to access **all** of the information in the packet. It might not seem very useful, but the idea is for plugins to be able to implement custom logic, using all of the information at their disposal.

I don't think it makes sense to remove access to that information - rather, explanation should be added about the potential uses of said data.

**Comment by zml2008** [comment]
imo that's the same as making an abstract packet API -- it ends up getting too close to the implementation. Anyways, plugins should not have to know anything about where the command's sender is coming from -- rcon, player, console, etc, just what attributes the sender has.

**Comment by Aaron1011** [comment]
@zml2008: The whole reason for having Rcon-specific events in the first place is for plugins to be able to get more information about the Rcon command sender.

If there's going to be Rcon-specific events at all, **all** of the available information should be exposed. Otherwise, there's no point in having any support for Rcon at all.

**Comment by me4502** [comment]
I mostly support this - except removing the ability to listen to what is actually being sent via RCon makes no sense at all.

**Pull request closed without merging**
