### PR TITLE
Add removal and clear methods to GameProfileCache

### PR DESCRIPTION
**Pull request by kashike**
[**API**](https://github.com/SpongePowered/SpongeAPI/pull/1244) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/720)

### CODE REVIEW

**Comment by simon816** [comment]
@kashike One thing I noticed about the `GameProfileCache` was that it isn't the right place to 'lookup' profiles. A cache should simply be a store of profiles, looking them up should be done by another service which is what `GameProfileManager` is for. It would be a bleeding change but what do you think about moving them to the `GameProfileManager`?

**Comment by kashike** [comment]
@simon816 `GameProfileCache` isn't just a "cache", it's a cache *and* a "loader". This allows plugins to change where everything is loaded from, since `GameProfileManager` is not a service (nor should it be, really, in my opinion).

**Comment by modwizcode** [comment]
Maybe `GameProfileManager` needs to be a service then? I think these changes should be done in another PR. This PR seems good.

**Comment by kashike** [comment]
I disagree, there's methods in there that can't be implemented by plugins.

**Pull request merged**
