### PR TITLE
Add BlockHarvestEvent, changes how silk touch enchant works

### PR DESCRIPTION
**Pull request by simon816**
I have created a new event, `BlockHarvestEvent` see the javadoc. 
This is the result from a previous PR, #422

### CODE REVIEW

**Comment by me4502** [comment]
im not sure about removing the dropped item from the break event, but otherwise I like it.

**Comment by Deamon5550** [comment]
@me4502 At the time of the BlockBreakEvent the dropped items aren't technically known, since that is the point of the BlockHarvestEvent (to determine what blocks should drop).

I wonder though if the BlockHarvestEvent should perhaps not be explicitly cancellable, since (unless I am misunderstanding the point of the harvest event) at that point the BlockBreakEvent has already been thrown and returned uncancelled so at this point it doesn't make much sense to cancel the harvest event (if you wanted no items to drop you could just clear the dropped items). Ehhh on second though perhaps it is less destructive to have it cancellable rather than forcing plugins to just clear the dropped items, makes it easier for another plugin to later uncancel it. Thoughts?

**Comment by ST-DDT** [comment]
So basically you replace the internal silk touch with an event driven one?
Except that one, i like the idea of this PR.

**Comment by me4502** [comment]
I vote keeping it cancellable, it's less destructive.

**Comment by me4502** [comment]
Maybe a way to get what enchantments have affected the output?

Eg, fortune

**Comment by ST-DDT** [comment]
Enchantment is to limited. Some plugins may want to add looting potions. So maybe this is something for our Cause System.
But then we should also use something like AttributeModifiers to keep track of all the changes.
This would also enable use to cancel the silk touch or fortune enchantment alone.

**Comment by me4502** [comment]
Pinging rest of @SpongePowered/developers for opinions.

**Comment by simon816** [comment]
After a draft implementation on top of forge's [`BlockEvent.HarvestDropsEvent`](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/event/world/BlockEvent.java#L45), I discovered a few potential issues.
Of course we should not be limited to how forge works, but there may be reasons for it among other things.
 - The drop chance is not always used, and sometimes completely ignored
 - The event is not cancellable
 - The event is fired after deciding whether it's a silk touch operation (hence why there is no `setSilkTouch(boolean)` method ATM)
 - Firing the event does nothing, it's only for listening

It'd be useful if someone could evaluate these points to see whether anything should be changed.

**Comment by me4502** [comment]
Our cancellable could just map to emptying the internal list of items in forge.

**Comment by me4502** [comment]
The last commit failed to build on travis

**Comment by simon816** [comment]
@me4502 There's going to be some issues when implementing this that I realized. I think it's because I was copying forge's event too closely.
I'm not sure whether `dropChance` should be part of the event since it's not always taken into account.
I think I should remove the event creation from `SpongeEventFactory` as it cannot be fired manually. (A plugin should either destroy the block or just spawn `Item` entities if they want to get a similar effect)
Was hoping my points above would have got a yay/nay before being merged.

**Comment by me4502** [comment]
Most events do nothing when fired, plugins can use it for support purposes.

**Comment by modwizcode** [comment]
@me4502 What do you mean "most events do nothing when fired"?

**Comment by me4502** [comment]
If a plugin fires a block break event, the block won't break, only the event will be fired.

**Comment by simon816** [comment]
Hmm so why would we want plugins to fire those events manually? It seems like that could confuse any plugins listening to that event.

**Comment by Xemiru** [comment]
could add a check to events to see if its from an actual game event or if its from a plugin. something like vanilla-only=true in the annotation so its not passed. separate pr, though.

**Comment by me4502** [comment]
Let's say a plugin wants to break a block. Before the break it, they send out the event to see if they're allowed to.

Plugins sending events is a very valid use case.

**Comment by ryantheleach** [comment]
Just to add, when plugins have historically thrown fake block place events they usually cancel them at the last possible moment in order to prevent logging plugins from logging the change.

**Comment by modwizcode** [comment]
Yeah I'm concerned about not differentiating between plugin checks and
vanilla events. What about a base event flag for isPlugin() that can be
checked to avoid doing things like adding a bonus when a plugin breaks a
block or something similar?

This needs some thought.

**Comment by ryantheleach** [comment]
This may have been merged, but I'm lost to where it's gone post event refactor. Has it just been removed or is there some other way to access the data, specifically looking at explosion drop rates.

**Comment by simon816** [comment]
@ryantheleach I think what you're after is [`DropItemEvent.Destruct`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/item/inventory/DropItemEvent.java#L79)
> `Called when one or more {@link Item} drops are triggered by an object such as an {@link Entity} or {@link BlockType} destruction.`

**Pull request merged**
