### PR TITLE
added parseResource method to ConfigFile.

### PR DESCRIPTION
**Pull request by thomas15v**
This will hopefully avoid duplicated code across plug-ins. It would be cleaner to read plug-in code that uses this method :).

Forum post: https://forums.spongepowered.org/t/help-me-understand-configuration/5582/3

### CODE REVIEW

**Comment by jk-5** [comment]
I agree in adding this method, but i don't agree with the name. The name doesn't imply that it saves the configuration file to disk. Maybe something like `parseAndSaveResource` is better

**Comment by thomas15v** [comment]
It doesn't save. But indeed maybe a force-save method will be better. Than could avoid extra duplicated code.

**Comment by jk-5** [comment]
Sorry. I first read the code and then the forum post so i accidentally thought this method saved too. Why not create such a method as mentioned in the forum post?

**Comment by thomas15v** [comment]
Idk, I was thinking. In case the dev wants to add something else before it saves the config. It would save it twice. And that not really efficient.

**Comment by thomas15v** [comment]
I just realise that this can't work without giving the plugin object as parameter. But wouldn't that look to messy?

**Comment by Zidane** [comment]
@sk89q 

Gonna let you make the call on this as you are adjusting the config API currently.

**Comment by sk89q** [comment]
We are contemplating replacing the configuration code entirely with something new.

Something similiar to https://github.com/sk89q/Eduardo/tree/master/src/main/java/com/sk89q/eduardo/util/config but with support for serialization of arbitrary objects.

**Comment by Zidane** [comment]
We've switched to configurate-hocon but thanks anyhow!

**Pull request closed without merging**
