### PR TITLE
Take advantage of Guava's ListenableFuture

### PR DESCRIPTION
**Pull request by PieGuy128**
- Add "runTask..." methods to AsynchronousScheduler that accept Callable as task parameter

- Make use of ListenableFuture to simplify retrieval of task computation results.

### CODE REVIEW

**Comment by Zidane** [comment]
This PR cannot be pulled, please rebase with latest master changes.

**Comment by PieGuy128** [comment]
I'm just embarrassing myself with my git-stupidity... Time to try again... :P

**Comment by ryantheleach** [comment]
Best bet is to not close PR's and just keep pushing to the branch in the PR, that way the history is recorded for people to review.

**Comment by PieGuy128** [comment]
That's the problem, the history contains a lie... (forgot to 'git config --global user.blah" before a commit, and pushed before I realized it!  Tehe...)

**Pull request closed without merging**
