### PR TITLE
Add CommandAuthorizationException

### PR DESCRIPTION
**Pull request by jacklin213**
The String permissionNode will need to be changed later on depending how the Permissions API is going to structure "permission nodes"

Deals with [SPONGE-44](http://issues.spongepowered.org/youtrack/issue/SPONGE-44)

### CODE REVIEW

**Comment by jacklin213** [comment]
Sorry what should I do with this now?

**Comment by modwizcode** [comment]
Here's what I was planning to do if you didn't have time/reply.

- [ ] Stash changes and do a reset to origin/master, then pop changes and move them into correct packages
- [ ] Leave the existing exceptions, because a ```CommandAuthorizationException``` is a ```CommandException```
- [ ] Handle CommandAuthorizationException with a default permission denied message of some sort. 
- [ ] (Optional) Add possible way to change default message by adding a parameter to command info definitions.

**Comment by ryantheleach** [comment]
Should the default message be customizable to the user, or to the plugin?

**Comment by modwizcode** [comment]
The plugin, if the plugin wants to let the user change the message that's
their choice.

**Comment by jacklin213** [comment]
@modwizcode I'll give that a go now

**Comment by modwizcode** [comment]
Ok thanks.

**Comment by jacklin213** [comment]
@modwizcode Sorry I did a really bad job there, is that what u meant by default message?

**Comment by modwizcode** [comment]
Haven't taken a look yet, mind explaining a bit more?

**Comment by jacklin213** [comment]
@modwizcode Well when u said default message I thoughtt u meant to code the default message into the ```CommandAuthorizationException``` class. So I did it like so 
```private static String defaultMessage = "You do not have the permission to use this command!";```
Which then changed the constructor to
```
public CommandAuthorizationException(String permissionNode, CommandCallable command) {
    this(defaultMessage, permissionNode, command);
}
```

But I'm pretty sure thats not the way to do it, is it?

**Comment by modwizcode** [comment]
Not quite. I'll be more specific in an hour or two.

**Comment by jacklin213** [comment]
@modwizcode That would be nice thanks :D

**Comment by modwizcode** [comment]
Sorry I took way longer than I thought. I meant to change the code in [SimpleCommandServer](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/service/command/SimpleCommandService.java) to have a second exception handler for CommandAuthorizationException that uses a default message there.

**Comment by jacklin213** [comment]
@modwizcode  Rebased and did what I thought you told me to :D

**Comment by modwizcode** [comment]
@jacklin213 Sorry I just looked at it again, I misread that logging warn as a message to the player. You shouldn't have to make any modifications to SimpleCommandServer.

**Comment by modwizcode** [comment]
Reset SimpleCommandServer and then it should be ready to merge.

**Comment by Zidane** [comment]
@modwizcode 

Finish this up and get it ready for merge please.

**Comment by modwizcode** [comment]
Closed in favor of continuation on https://github.com/SpongePowered/SpongeAPI/pull/455

**Pull request closed without merging**
