### PR TITLE
Fixes check style errors alongside some other minor cleanup for bleeding

### PR DESCRIPTION
**Pull request by parlough**
Accomplishes a few things.

- Updates the Checkstyle version we were using.
- Merges some of the upstream checkstyle file changes from checkstyle/google
- Fixes a lot of spelling errors
- Adds some missing Javadocs
- Consolidates all of the package info files to one format and adds some missing ones
- Fixes the Javadocs errors on build
- Removes unused imports
- Fixes some minor issues here and there, mostly all relating to formatting

We are now closer to following our own style guide. Not completely there yet but we'll get there.

I tested the changes to a basic extent make sure I didn't break something accidentally. Seemed to go fine.

I split most of the changes into coherent commits, but one or the two commits didn't get commited fully so some of their changes are in the next commit, and other commits just have general fixes.

Eventually I will come back and cleanup remaining Javadocs even more and add some to places where they are quire needed, such as some properties and the listings of some catalog types.

### CODE REVIEW

**Comment by ryantheleach** [comment]
Given the sheer size of this PR, I would like to see an automated report on the API signature changes before and after. 

If it's largely just checkstyle changes, I would expect there to be no or minimal changes.

Maybe try using : 
https://github.com/siom79/japicmp
http://clirr.sourceforge.net/
https://revapi.org/ 
https://github.com/lvc/japi-compliance-checker
???

**Comment by stephan-gh** [comment]
Awesome! There still seem to be 3 minor checkstyle warnings: https://travis-ci.org/SpongePowered/SpongeAPI/jobs/331403350#L605-L607, can you fix these too? :)

**Comment by parlough** [comment]
@Minecrell Done, I just had an uppercase J instead of a lowercase...

**Review by gabizou — APPROVED** [review]

**Comment by ryantheleach** [comment]
For what it's worth, Guava uses JDiff http://google.github.io/guava/releases/23.0/api/diffs/changes/pkg_com.google.common.collect.html

https://sourceforge.net/projects/javadiff/

**Comment by parlough** [comment]
@ryantheleach Here, I generated this report. There are a few breaking changes, but I do not believe they will affect many if anyone at all. I intend to leave most of these changes in bleeding anyway.

I used japicmp.

[output.zip](https://github.com/SpongePowered/SpongeAPI/files/1653866/output.zip)

**Edit:** Actually here, this one will probably be easier to read. This shows only the changes:

[output-changes.zip](https://github.com/SpongePowered/SpongeAPI/files/1653924/output-changes.zip)

This is actually pretty cool, simple to use, and would be cool to include with our API builds in some fashion. At least for the major releases.

**Comment by parlough** [comment]
When I do merge this, should I squash the commits or no? If I don't it will be easier to track down changes as well as cherry-pick any changes if that's desired.

**Comment by ryantheleach** [comment]
I wonder considering the small number of incompatible changes, if it's better off getting the bulk of this into stable, and only having the incompatible changes in bleeding?

If I realized you were targeting bleeding from the start, I wouldn't have asked for the report, sorry.

**Comment by parlough** [comment]
@ryantheleach Thinking about it more. I will branch off from this, creating a branch which targets stable and removes the breaking changes. I will also fix any merge conflicts that arise from the target differences.

**Comment by parlough** [comment]
You can find the 7.1/stable-7 version of this PR here: https://github.com/SpongePowered/SpongeAPI/pull/1747

**Pull request merged**
