### PR TITLE
Fix BeaconData to match it's Keys

### PR DESCRIPTION
**Pull request by jamierocks**

### CODE REVIEW

**Comment by JBYoshi** [comment]
I think the `Key`s are supposed to be `Optional`. I'm pretty sure `BeaconData` is already correct.

**Comment by Aaron1011** [comment]
@jamierocks: Doesn't this need to be an `OptionalValue`, since a `PotionEffectType` isn't always set?

**Comment by JBYoshi** [comment]
@Aaron1011 Hey, I said that! :smile:

**Comment by jamierocks** [comment]
I'm going to check if it's always set.

**Comment by jamierocks** [comment]
Okay, there is a potential this might not be set, updating pr.

**Comment by Aaron1011** [comment]
Closed in https://github.com/SpongePowered/SpongeAPI/commit/c64e2a94e85032196bc54448583c2cccfe1eab24

**Pull request closed without merging**
