### PR TITLE
Add setter for the PotionEffect in ChangeEntityPotionEffectEvent

### PR DESCRIPTION
**Pull request by pie-flavor**
This should be able to be modified without cancelling the event.

### CODE REVIEW

**Comment by liach** [comment]
Please use four spaces instead of tabs.

**Comment by liach** [comment]
```java
    /**
     * Gets the potion effect involved in this event, handled by previous plugins.
     *
     * @return The potion effect involved in this event
     */
    PotionEffect getModifiedPotionEffect();
	
    /**
     * Sets the new potion effect to be used in this event.
     *
     * @param effect The potion effect to be used
     */
    void setPotionEffect(PotionEffect effect);
```
These two methods should be in `Gain` sub-interface as this has no meaning to other two interfaces.

**Comment by ryantheleach** [comment]
The second you start letting the effect be mutable, you should also have a getOriginalEffect.

**Comment by liach** [comment]
@ryantheleach If you do this change you should retarget bleeding, because the old `getPotionEffect()V` returns the original effect.

**Pull request closed without merging**
