### PR TITLE
Slight refactor of SimpleDispatcher to support SpongePowered/SpongeCommon#2385

### PR DESCRIPTION
**Pull request by dualspiral**
**SpongeAPI** | [SpongeCommon](https://github.com/SpongePowered/SpongeCommon/pull/2385) | [Original Issue](https://github.com/SpongePowered/SpongeAPI/issues/2048)

This PR is mostly to remove the `final` modifier from `SimpleDispatcher` and rearrange a little bit of logic to support the goals of SpongePowered/SpongeCommon#2385 and SpongePowered/SpongeAPI#2048.

Big thing here is removing the `final` modifier. I don't see it as a problem. However, if we are not okay with that, that's okay, but the whole Dispatcher will be copied into Common.

Please see the Common PR for a lot more information as to what this will achieve.

---

* Move some logic into protected methods to reduce deduplication
* As this was final, no previous plugins will have extended this - changes are safe.
* Logic has not changed except for a reversion (below) that will go into the impl instead.
* Revert "Filter CommandMapping result based on source permission.", this reverts commit b38390e1751fff802d355155c45b2eb4913f5817 (the spirit of this will be in the Common PR).

### CODE REVIEW

**Comment by liach** [comment]
can't you just make a command dispatcher that use this one in a field and just delegate most calls?

**Comment by liach** [comment]
and if you do decide to remove final, consider making some fields protected

**Comment by dualspiral** [comment]
> can't you just make a command dispatcher that use this one in a field and just delegate most calls?

It becomes tricky to ensure that the common PR can do what it does without copying huge chunks of code - if you read how the common PR works compared to this you'll see that the `get` method requires a third parameter there - and not being able to override methods would have severely hampered what I was trying to do.

Quite frankly, I'm not wasting more time on something that is going to be gutted in API 8 anyway. The only reason I've done it this way is to minimise the code duplication, such that if we _do_ need to change some logic to fix a bug or whatever, we're not duplicating these fixes. There may be others using such a dispatcher.

It's either this or copying it into common. I've made no secret about that, it's something I muse upon in the Common PR. It's a draft because I'm not sure I want to do this at all, and I simply want opinions on final vs. non final from @gabizou and @Zidane.

> consider making some fields protected

No. I am simply going to do what is necessary to support the implementation. Honestly, this class should not be in the API layer at all and so, without breaking things, I'm going to consider it as implementation. If someone then wants something to be exposed for whatever reason, they can PR it, but again, I see little reason to.

**Comment by dualspiral** [comment]
I've talked to @Zidane about this, and all I'm going to do is copy this into Common - no-one should be using this anyway...

**Pull request closed without merging**
