### PR TITLE
Add Text methods for working with Teams

### PR DESCRIPTION
**Pull request by kashike**
This adds `Text` methods to `Team` for adding "fake players" to a scoreboard team. This is helpful when [using `Text` scores](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/scoreboard/Scoreboard.java#L109-L124).

See https://github.com/SpongePowered/SpongeAPI/pull/739#issuecomment-116238966 for a more detailed explanation.

*(...and the worst PR description award goes to...)*

### CODE REVIEW

**Comment by ST-DDT** [comment]
The method naming is a little bit strange.
Maybe you should call it `getNames` instead of `getTexts`. Wouldn't it be possibe to add fake players via fake `User`s using the existing methods?

Also I'm not sure how this improves functionality. Could you please add an example usage to your PR description?

**Comment by kashike** [comment]
@ST-DDT

I agree that the method names aren't the best, but I couldn't think of better. `getNames` would make me believe I'm getting *all* names of entries.
I opened this PR after talking with @Aaron1011 a few times the past few months.

Example usage:
I create a `Score` of `Texts.of("Kittens")` and set the value to `10`. The maximum length a name can have is `32`, including colouring. If you add the "player" to a scoreboard `Team`, however, you have an available length of `64` due to the team prefix and suffix, allowing for more content/colouring. In addition to the length, you can change the way the score is rendered on the scoreboard by using a "blank" score name (that is, of a formatting character) and setting the prefix and suffix alone.

Apologies in advance if this doesn't make much sense, it's 2:28 am here.

**Comment by ST-DDT** [comment]
@kashike 

> I agree that the method names aren't the best, but I couldn't think of better. getNames would make me believe I'm getting all names of entries.

Then how about `getFakeNames()` or  `getFakeMembers()`?

The example is good/understandable. Thanks for writing it. I was just confused because in `Team`s members where addressed as `User`s and in `Scoreboard`s they are represented as `Text`s.

**Comment by kashike** [comment]
@ST-DDT 

If I'm going to rename `getTexts`, I'd like to rename `addText` and `removeText` to something that matches. I was thinking something along the lines of: `getFakeEntries`, `addFakeEntry` and `removeFakeEntry`.

Do you, or anyone else, have better names?

**Comment by TheRaspPie** [comment]
As far as I know the scoreboard in Vanilla isn't bound to any user, it's basically just a JSON formatted text. So I would suggest removing the `User`-based methods completely or keeping them for convenience and renaming the `Text`-based methods to `addEntry`, `removeEntry` and `getEntries` because these entries aren't in any way "fake".

**Comment by Aaron1011** [comment]
Closed in https://github.com/SpongePowered/SpongeAPI/commit/2cd91adf9eb9399f9f2f7688531d5ba744b8b738

**Pull request closed without merging**
