### PR TITLE
Added BlockRedstoneUpdateEvent.

### PR DESCRIPTION
**Pull request by me4502**
Adds a redstone event that extends BlockUpdateEvent.

### CODE REVIEW

**Comment by me4502** [comment]
Making this cancellable may cause issues internally - the game does not respond kindly to these kinds of updates not occuring.

**Comment by modwizcode** [comment]
Pretty sure Bukkit let you cancel, which, while justifying an API choice by
saying "Bukkit did it" isn't a real strong support, I think that this is a
case that plugins actively used.

By providing this mechanic would make some plugins completely impossible.

Going to ask @SpongePowered/developers for comment here as I feel we should
decide this as a team.

**Comment by me4502** [comment]
From what I can tell, Bukkit didn't provide this functionality.

**Comment by modwizcode** [comment]
Hmm. Well if it didn't let you cancel, it at least gave you previous state,
new state (strength) and let you set both actually. Which is the
functionality I meant by cancelable.

**Comment by me4502** [comment]
This allows setting new - setting old is quite redundant.

**Comment by modwizcode** [comment]
Wasn't quite sure but after thinking about it some more I realized that's
correct. Setting old is undesirable as well as unnecessary. I missed the
method to set a new value somehow.

Given that, barring any formatting and style concerns I can't check now,
this seems good.

**Comment by me4502** [comment]
The style all checks out.

**Comment by modwizcode** [comment]
Ok will merge

**Comment by me4502** [comment]
I'll do it, already got it locally

**Comment by modwizcode** [comment]
Yeah sorry, I normally work with non-core PRs

**Comment by me4502** [comment]
Yeah, all fine

**Pull request closed without merging**
