### PR TITLE
Switch to using event-impl-gen in its AP form

### PR DESCRIPTION
**Pull request by zml2008**
See https://github.com/SpongePowered/event-impl-gen/pull/12

This is the changes necessary to update for that PR, tracking in a PR until I've had a chance to test these changes more thoroughly.

### CODE REVIEW

**Comment by zml2008** [comment]
This will be ready to merge once Gradle 7.2 is released, fixing issues with incremental compilation.

**Comment by Zidane** [comment]
@zml2008 

ETA on 7.2?

**Comment by zml2008** [comment]
7.2's RC1 is scheduled for Monday (via https://github.com/gradle/gradle/milestone/174) -- I expect the final release will be a few weeks after that. This PR should maintain an identical API for users -- there was one generics change necessary, but that has been applied to the `api-8` branch separately.

**Comment by dualspiral** [comment]
What's our thinking on this - merge conflicts aside are we ready to go with this?

**Comment by zml2008** [comment]
there are still some issues with incremental builds in intellij that I haven't had a chance to resolve yet - I think that's the only blocker though

**Comment by ImMorpheus** [comment]
@zml2008 Are those still an issue ? What's the status of this ?

**Comment by zml2008** [comment]
I think the blocker here is still incremental processing unfortunately

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please rebase this PR on the current branch and reopen it.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1

**Pull request closed without merging**
