### PR TITLE
Add Acceleration Data

### LINKED ISSUE #1981: Unable to adjust the Entity "power" tag for Fireballs.
Description of the tag by the Official Minecraft Wiki:

> power: List of 3 doubles that adds to direction every tick. Act as the acceleration.
   ~ [Official Minecraft Wiki - Ghast](https://minecraft.gamepedia.com/Ghast#Ghast_fireball)

Just from reading this description you can see why, when altering the course of a Fireball entity, you would need to be able to adjust this tag.

### PR DESCRIPTION
**Pull request by Grinch**
**SpongeAPI** | [SpongeCommon](https://github.com/SpongePowered/SpongeCommon/pull/2303)

Resolves #1981 

Signed-off-by: Steven Downer <grinch@outlook.com>

### CODE REVIEW

**Comment by liach** [comment]
:tada: Finally we don't need to register an event listener to constantly change the velocity of the fireball like in the cookbook!

**Comment by Pulverizer** [comment]
This variable is also needed for WitherSkull.

**Comment by Grinch** [comment]
@Pulverizer Updated based on your feedback.

**Comment by NeumimTo** [comment]
may this affect any entity?

**Comment by Pulverizer** [comment]
There may be some entities we've missed. But in vanilla, it only affects certain entities.

Maybe it should be discussed if we want to modify Minecraft to have it for all entities.

**Pull request merged**
