### PR TITLE
1.13 - The Technical and Aquatic Update

### PR DESCRIPTION
**Pull request by Cybermaxke**
Very WIP, I am opening this PR now to start a discussion on what can be reused/needs to be removed. Also designing a system to easily get variants of certain block types. For example getting a slab with the material oak.

Related to:
https://github.com/SpongePowered/SpongeAPI/pull/1715 - The variant system
https://github.com/LanternPowered/LanternServer/pull/48
https://github.com/SpongePowered/SpongeAPI/pull/1742

We have to decide what to do with the following data types, could it be reused for the variant system or should be deleted. I already removed a few types, feel free to comment if you don't agree with me removing them.

#### Modify/remove:

Catalog types and data:
- [x] BrickTypes - _Removed_
- [x] BrickData - _Removed_
- [x] CoalTypes - _Removed_
- [x] CoalData - _Removed_
- [x] CookedFishes - _Removed_
- [x] CookedFishData - _Removed_
- [x] DirtTypes - _Removed_
- [x] DirtData - _Removed_
- [x] DisguisedBlockTypes - _Removed_
- [x] DisguisedBlockData - _Removed_
- [x] DoublePlantTypes - _Removed_
- [x] DoublePlantData - _Removed_
- [x] DyeColors - _Still used by other data types, used in variant system_
- [x] DyeableData - _Still used by other data types_
- [x] Fishes - _Removed_
- [x] FishData - _Removed_
- [x] LogAxes _- Removed, bark got separated from log, log uses now the Axis_
- [x] LogAxisData - _Removed_
- [x] GoldenApples - _Removed_
- [x] GoldenAppleData - _Removed_
- [x] PistonTypes - _Removed_
- [x] PistonData - _Removed_
- [x] PlantTypes - _Removed_
- [x] PlantData - _Removed_
- [x] PrismarineTypes - _Removed_
- [x] PrismarineData - _Removed_
- [x] SandstoneTypes - _Removed_
- [x] SandstoneData - _Removed_
- [x] SandTypes - _Removed_
- [x] SandData - _Removed_
- [x] ShrubTypes - _Removed_
- [x] ShrubData - _Removed_
- [x] SkullTypes - _Removed_
- [x] SkullData - _Removed_
- [x] SlabTypes - _Removed_
- [x] SlabData - _Removed_
- [x] StoneTypes - _Removed_
- [x] StoneData - _Removed_
- [x] TreeTypes - _Will be used in the variant system_
- [x] TreeData - _Removed_
- [x] WallTypes - _Removed_
- [x] WallData - _Removed_
- [x] QuartzTypes - _Removed, separate blocks, pillar variant now uses the Axis._
- [x] QuertzData - _Removed_
- [x] BigMushroomTypes - _Removed, replaced with BigMushroomPoresData_
- [x] BigMushroomData - _Removed, replaced with BigMushroomPoresData_

Other data (and keys):
- [x] SeamlessData - _Removed_
- [ ] SpawnableData

Tile entities:
- [x] Note - _Removed_
- [x] Skull - _Removed_
- [x] FlowerPot- _Removed_

#### New/Modified

Data (probably separate PRs):
- [x] LitData - _New_ (furnaces, redstone torch, redstone)
- [x] InstrumentData - _New_ (note block)
- [x] SlabPortionData (and SlabPortion) - _New_
- [x] ChestAttachmentData (and ChestAttachmentType) - _New_
- [x] InvertibleData - _New_ (daylight sensor)
- [x] SurfaceAttachmentData (floor, ceiling, wall) - _New_ (buttons, lever), is this a good name?
- [x] BigMushroomPoresData - _New_ (replaces BigMushroomData)
- [ ] UnstableData - _New_ (TNT)

Tile entities:
- [x] Player head - _New_

Populators:
- [x] Merged Shrub and Flower into Plant

Other:
- [x] Update statistics, moved to https://github.com/SpongePowered/SpongeAPI/pull/1742
- [x] Update block traits
- [x] Update particles
- [x] RecordType -> MusicDisc - In 1.13, the name 'record' is no longer used in any translation keys, item ids, etc. (item names were already Music Discs)
- [ ] ~~Remove extended block states? Everything is now controlled server side.~~ - Forge is still going to use them.

### CODE REVIEW

**Comment by MattBDev** [comment]
Is there any rough eta on when this may be pushed to the breaking branch?

**Comment by Cybermaxke** [comment]
@MattBDev There is no eta, we haven't even started updating the sponge implementations yet.

**Comment by MattBDev** [comment]
@Cybermaxke I didn't even think about the implementations. Thanks for the reply though.

**Comment by Zidane** [comment]
Closing as 1.13 is our in-dev branch, not bleeding for this.

**Pull request closed without merging**
