### PR TITLE
Add AuthorData which represents the author of a book

### PR DESCRIPTION
**Pull request by Grinch**
Signed-off-by: Steven Downer <grinch@outlook.com>

### CODE REVIEW

**Comment by ST-DDT** [comment]
After a first check i have seen PagedData.
But havent seen Title and SubtitleData or GenerationData lately. Do they (still) exist? Or could you add them as well?

**Comment by Grinch** [comment]
@ST-DDT TitleData is now there (literally just pushed it). Not sure what you mean for Subtitle data. Could you elaborate?

**Comment by ST-DDT** [comment]
Oh i mixed that up with the title screen.
But books have a generation. Original, CopyOfOriginal, CopyOfCopy. Is there something in the API yet? Afaik it had been at some point. I guess before zhe unified data api

**Comment by Grinch** [comment]
@ST-DDT After listening to what @gabizou has done, DisplayNameData handles titles for books and CloneableData handles generation data for books.

**Comment by gabizou** [comment]
Added in 6b7623

**Comment by TheAwesomeGem** [comment]
Looks great!

**Pull request closed without merging**
