### PR TITLE
instrumentData and AxisData removal

### PR DESCRIPTION
**Pull request by lucdon**
InstrumentData isnt possible to implement
AxisData is only used in quartzBlocks only that is better to handle by just adding the axis to QuartzTypes(which is how minecraft handles EnumQuartzType)

### CODE REVIEW

**Comment by AlphaModder** [comment]
@lucdon Why can't we use insturmentdata?

**Comment by ryantheleach** [comment]
Because it's entirely dependent on the block below the noteblock, not the noteblock itself. I'm confused at why wood and quartz don't use axis data however.

**Comment by gabizou** [comment]
@ryantheleach Because they are very specific in that they don't just accept `Axis` values, there's [`LogAxss`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/type/LogAxes.java#L31), and soon, `QuartzAxes`.

**Comment by JBYoshi** [comment]
@gabizou Why don't logs and quartz just use the same `Axis` class?

**Pull request closed without merging**
